### PR TITLE
Add Rust 🚀🚀🚀

### PR DESCRIPTION
**Pull request by juni-purr**
guh???

This program is written in Rust 🚀, meaning it is:
- 🚀 Memory Safe
- 🚀 Fast
- 🚀 Not crappy
- 🚀 No external libraries
- 🚀 1498021348129 compile errors

🚀 Epic 🚀 Screenshots 🚀
image
100x100
image

PS: It also includes a `shell.nix` file for anyone who doesn't want to bother installing the rust toolkit on their computer 🚀🚀🚀🚀🚀🚀🚀

🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

### CODE REVIEW

**Comment by steviegt6** [comment]
🚀 🚀 🚀 🚀 🚀

**Comment by ppebb** [comment]
In the very last columns and rows, such as between 462 and 484, there are 2 spaces when there should only be one. Seems you have additional spacing between everything.

**Comment by kenos1** [comment]
Yeah that was fixed in https://github.com/ppebb/multtable/pull/13/commits/e51842c6e112b904662137f998cb304e9c20f596

**Comment by ppebb** [comment]
oh, lgtm then!!

**Comment by juni-purr** [comment]
guh????

**Pull request merged**
